### ISSUE TITLE
Invalid Swift Support - file mismatch AppStore

### ISSUE THREAD

**Issue by luconlua** [Flash3001/iOSCharts.Xamarin#26]
I've  installed iOSCharts 3.0.2 with Xamarin.Swift3 3.0.1.
I use this guide (step 7) to create the ipa file: 
[https://stackoverflow.com/documentation/xamarin.ios/6091/binding-swift-libraries#t=201706061816009600675
](url)
But I don't get it.  The Message from apple:
Invalid Swift Support - The files libswiftDarwin.dylib, libswiftCoreData.dylib, libswiftUIKit.dylib, libswiftObjectiveC.dylib, libswiftQuartzCore.dylib, libswiftos.dylib, libswiftCore.dylib, libswiftFoundation.dylib, libswiftCoreAudio.dylib, libswiftCoreGraphics.dylib, libswiftCoreImage.dylib, libswiftCoreMedia.dylib, libswiftDispatch.dylib don’t match /Payload/My.app/Frameworks/libswiftDarwin.dylib, ......

Environment:
Xamarin Studio Version 6.3 (build 863)
Runtime:
	Mono 4.8.1 (mono-4.8.0-branch/22a39d7) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
=== NuGet ===
Version: 3.5.0.0
=== Apple Developer Tools ===
Xcode 8.3.1 (12170)
=== Xamarin.iOS ===
Version: 10.8.0.175 (Xamarin Studio Community)

**Comment by Flash3001** [comment]
@luconlua This issue happens because the version of Xcode and the SwiftSupport version you are using are not compatible.

For Xcode 8.3.1 use the versions 3.1.0.1
For Xcode 8.3.2 use the versions 3.1.0.2

You can check a list of version for the packages in here: https://www.nuget.org/packages/Xamarin.Swift3.Core/3.1.0.1

**Comment by luconlua** [comment]
It works
thx
