### ISSUE TITLE
Error building target _BeforeCoreCompileInterfaceDefinitions

### ISSUE THREAD

**Issue by kevinlcfei** [Flash3001/iOSCharts.Xamarin#3]
Hi Flash,

After update the latest version of 2.2.3.8 in Xamarin Studio Nuget. There is issue occur while building the apps.

> Error: Error building target _BeforeCoreCompileInterfaceDefinitions: Could not load file or assembly '/Users/kevinloke/Documents/SVN/Mobile/XilnexOTM/packages/iOSCharts.2.2.3.8/build/Xamarin.iOS.Tasks.dll' or one of its dependencies (XilnexOTM.iOS)

Do you have any idea which causing this issue?

**Comment by Flash3001** [comment]
Which version of Xamarin Studio and Xamarin.iOS are you using?

**Comment by Flash3001** [comment]
@kevinlcfei Open the file '/Users/kevinloke/Documents/SVN/Mobile/XilnexOTM/packages/iOSCharts.2.2.3.8/build/iOSCharts.targets' and remove the following lines:

`<UsingTask TaskName="Microsoft.Build.Tasks.Copy" AssemblyFile="Xamarin.iOS.Tasks.dll"/>
    <UsingTask TaskName="Microsoft.Build.Tasks.RemoveDir" AssemblyFile="Xamarin.iOS.Tasks.dll"/>
    <UsingTask TaskName="Microsoft.Build.Tasks.Delete" AssemblyFile="Xamarin.iOS.Tasks.dll"/>`

Or just go back to 2.2.3.7.

It will make it work for now. Meanwhile I'll try to find a solution that make it work fine on both Visual Studio and Xamarin Studio.

The problem is that I need to move some files around when compiling for Simulator. When building on a Mac it just works fine. But when using Visual Studio it needs to make changes on the building host as well. Delete, Move and Copy tasks from Microsoft.Build.Tasks don't do it, just the ones from Xamarin.iOS.Tasks.

**Comment by kevinlcfei** [comment]
@Flash3001 
I'm using Xamarin Studio Business
Version 5.10.3 (build 51)
Runtime:
    Mono 4.2.4 (explicit/71b88f3)
    GTK+ 2.24.23 (Raleigh theme)

Apple Developer Tools
Xcode 7.3.1 (10188.1)
Build 7D1014

Xamarin.iOS
Version: 9.6.2.4 (Xamarin Business)

Operating System
Mac OS X 10.11.5

Testing on submitting apps via application loader.

> - Error Messages:
>     Communication error. Please use diagnostic mode to check connectivity. You need to have outbound access to TCP port 443.
>     An exception has occurred: Operation timed out
>     ERROR ITMS-90668: "Invalid Bundle Executable. The executable file 'XilnexOTM.iOS.app/Frameworks/Charts.framework/Charts' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

I tried to resubmit the apps with ver2.2.3.7 and ver2.2.3.8. Having the same issue for Charts frameword - enable bitcode.

**Comment by Flash3001** [comment]
@kevinlcfei That's new to me. I was able to send my app to Apple using 2.2.3.7. I'll try to figure it out.

**Comment by kevinlcfei** [comment]
@Flash3001 Could you released a version with enable bitcode = false in the xcode. Let give this a try?

**Comment by Flash3001** [comment]
Done! Please try it again and tell me if it worked. 
New version: 2.2.3.9

**Comment by kevinlcfei** [comment]
@Flash3001 Its worked. thanks
Using version 2.2.4
