### ISSUE TITLE
Line chart - Marker view crashed on device but works fine in Simulator

### ISSUE THREAD

**Issue by sksjolly** [Flash3001/iOSCharts.Xamarin#33]
Hi,
We are trying to implement line chart in Xamarin for iOS.
On tapping on the graph ,app get crashes on device but able to see the Marker View in Simulator.Please find the implementation

 Extending MarkerPopupView class from ChartMarkerView

 ```
public partial class MarkerPopupView : ChartMarkerView
    {
        public static readonly NSString Key = new NSString("MarkerPopupView");
        public static readonly UINib Nib;

        static MarkerPopupView()
        {
            Nib = UINib.FromName("MarkerPopupView", NSBundle.MainBundle);
        }

        protected MarkerPopupView(IntPtr handle) : base(handle)
        {
            // Note: this .ctor should not contain any initialization logic.
        }

        public static MarkerPopupView Create()
        {
            return (MarkerPopupView)Nib.Instantiate(null, null)[0];
        }

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();
        }

        public override void RefreshContentWithEntry(ChartDataEntry entry, ChartHighlight highlight)
        {
            base.RefreshContentWithEntry(entry, highlight);
        }
    }

```
Calling this method from Chartview class

            var markerView = MarkerPopupView.Create();
            chartView.Marker = markerView;
            chartView.DrawMarkers = true;

App crashes on tapping on the graph  by changing the below property to true in device but works fine in simulator,and no markerView is shown when the property is changed to false for both device and simulator.

          chartView.HighlightPerTapEnabled = false;

is it possible add Markerview in line chart?

Any help would be appreciated!!!

**Comment by Flash3001** [comment]
@sksjolly Unfortunately I don't have a good answer to that as there is a open ticket with the same root issue #11 

The problem is that you can't inherit from a Swift class (you can't do that even when you use it on ObjectiveC). I'm not sure if that is the final answer to the problem as I'm doing some research on that.

The solution is to implement the interface and inherit from NSObject. Look at how in here: https://github.com/Flash3001/iOSCharts.Xamarin/issues/11#issuecomment-319378791
